baseURL = "https://heathhenley.github.io/"
languageCode = "en-us"
title = "Blogging by Heath™"
theme = "pickles"

# Google Analytics API key.
googleAnalytics = "UA-48985842-4"

paginate = 3

[params]
  custom_css = ["/css/custom.css"]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  instagram = "feel_the_heath"
  github = "heathhenley"
  linkedin = "hhenley"
  author = "Heath Henley"
  avatar = "/heathcropped.png"
  contact = "mailto:heath.j.henley@gmail.com"
  bio = "Just your average software developing, sonar data processing rockclimber with a taste for computational thermodynamics and cookies."
  favicon = "/favicon.png"
# Short subtitle/tagline. This is displayed in the header.
#  subtitle = ""
#  logo = "/path/to/logo"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "Tutoring"
    url = "/tutoring"
    weight = 4

[[menu.main]]
    name = "Writing"
    url = "/writing"
    weight = 5

[[menu.main]]
    name = "ESOL Class"
    url = "https://sites.google.com/view/english-at-pcl/home"
    weight = 6

[[menu.main]]
    name = "Photography"
    url = "https://hhenley.darkroom.tech/"
    weight = 7
