baseURL = "https://heathhenley.github.io/"
languageCode = "en-us"
title = "Blogging by Heath™"
theme = "pickles"

[params]
  paginate = 5
  custom_css = ["/css/custom.css"]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  instagram = "keith_with_an_h"
  github = "heathhenley"
  linkedin = "hhenley"
  twitter = "Heath_Henley"
  author = "Heath Henley"
  avatar = "/heathcropped.png"
  contact = "mailto:heath.j.henley@gmail.com"
  bio = "Just your average software developing, sonar data processing rockclimber with a taste for computational thermodynamics and cookies."
  favicon = "/favicon.png"
  meta_description = "Chemical Engineer turned Software Engineer writing about Python, C++, computer simulation methods, full stack application development, CI/CD, travel, and whatever else comes up that seems worth sharing."


#  logo = "/path/to/logo"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "Tutoring"
    url = "/tutoring"
    weight = 4

[[menu.main]]
    name = "Writing"
    url = "/writing"
    weight = 5

[[menu.main]]
    name = "ESOL Class"
    url = "https://sites.google.com/view/english-at-pcl/home"
    weight = 6

[[menu.main]]
    name = "Photography"
    url = "https://gobeoutside.darkroom.com/"
    weight = 7

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
